// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message_internal.go.tmpl

package internal

import (
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon/utils"
)

type Resource struct {
	orig  *otlpresource.Resource
	state *State
}

func GetOrigResource(ms Resource) *otlpresource.Resource {
	return ms.orig
}

func GetResourceState(ms Resource) *State {
	return ms.state
}

func NewResource(orig *otlpresource.Resource, state *State) Resource {
	if orig == nil {
		orig = &otlpresource.Resource{}
	}
	return Resource{orig: orig, state: state}
}

func GenerateTestResource() Resource {
	orig := otlpresource.Resource{}
	state := StateMutable
	tv := NewResource(&orig, &state)
	FillTestResource(tv)
	return tv
}

func FillTestResource(tv Resource) {
	FillTestMap(NewMap(utils.Ref(tv.orig.GetAttributes()), tv.state))
	tv.orig.SetDroppedAttributesCount(uint32(17))
}
