// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message_internal.go.tmpl

package internal

import (
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
)

type InstrumentationScope struct {
	orig  *otlpcommon.InstrumentationScope
	state *State
}

func GetOrigInstrumentationScope(ms InstrumentationScope) *otlpcommon.InstrumentationScope {
	return ms.orig
}

func GetInstrumentationScopeState(ms InstrumentationScope) *State {
	return ms.state
}

func NewInstrumentationScope(orig *otlpcommon.InstrumentationScope, state *State) InstrumentationScope {
	if orig == nil {
		orig = &otlpcommon.InstrumentationScope{}
	}
	return InstrumentationScope{orig: orig, state: state}
}

func GenerateTestInstrumentationScope() InstrumentationScope {
	orig := otlpcommon.InstrumentationScope{}
	state := StateMutable
	tv := NewInstrumentationScope(&orig, &state)
	FillTestInstrumentationScope(tv)
	return tv
}

func FillTestInstrumentationScope(tv InstrumentationScope) *otlpcommon.InstrumentationScope {
	tv.orig.SetName("test_name")
	tv.orig.SetVersion("test_version")
	tv.orig.SetAttributes(FillTestMap(NewMap(&[]*otlpcommon.KeyValue{}, tv.state)))
	tv.orig.SetDroppedAttributesCount(uint32(17))
	return tv.orig
}
