// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package plog

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	otlplogs "go.opentelemetry.io/collector/pdata/internal/data/protogen/logs/v1"
)

// ResourceLogsSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type ResourceLogsSliceAccessor interface {
	SetResourceLogs([]*otlplogs.ResourceLogs)
	GetResourceLogs() []*otlplogs.ResourceLogs
}

// ResourceLogsSlice logically represents a slice of ResourceLogs.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewResourceLogsSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ResourceLogsSlice struct {
	orig  ResourceLogsSliceAccessor
	state *internal.State
}

func newResourceLogsSlice(orig ResourceLogsSliceAccessor, state *internal.State) ResourceLogsSlice {
	return ResourceLogsSlice{orig: orig, state: state}
}

// NewResourceLogsSlice creates a ResourceLogsSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewResourceLogsSlice() ResourceLogsSlice {
	state := internal.StateMutable
	return newResourceLogsSlice(&otlplogs.LogsData{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewResourceLogsSlice()".
func (es ResourceLogsSlice) Len() int {
	return len(es.orig.GetResourceLogs())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ResourceLogsSlice) At(i int) ResourceLogs {
	return newResourceLogs(es.orig.GetResourceLogs()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ResourceLogsSlice can be initialized:
//
//	es := NewResourceLogsSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ResourceLogsSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetResourceLogs())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlplogs.ResourceLogs, len(es.orig.GetResourceLogs()), newCap)
	copy(newOrig, es.orig.GetResourceLogs())
	es.orig.SetResourceLogs(newOrig)
}

// AppendEmpty will append to the end of the slice an empty ResourceLogs.
// It returns the newly added ResourceLogs.
func (es ResourceLogsSlice) AppendEmpty() ResourceLogs {
	es.state.AssertMutable()
	es.orig.SetResourceLogs(append(es.orig.GetResourceLogs(), &otlplogs.ResourceLogs{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ResourceLogsSlice) MoveAndAppendTo(dest ResourceLogsSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetResourceLogs() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetResourceLogs(es.orig.GetResourceLogs())
	} else {
		dest.orig.SetResourceLogs(append(dest.orig.GetResourceLogs(), es.orig.GetResourceLogs()...))
	}
	es.orig.SetResourceLogs(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ResourceLogsSlice) RemoveIf(f func(ResourceLogs) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetResourceLogs()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetResourceLogs()[newLen] = es.orig.GetResourceLogs()[i]
		newLen++
	}
	es.orig.SetResourceLogs(es.orig.GetResourceLogs()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ResourceLogsSlice) CopyTo(dest ResourceLogsSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetResourceLogs())
	if srcLen <= destCap {
		dest.orig.SetResourceLogs(dest.orig.GetResourceLogs()[:srcLen:destCap])
		for i := range es.orig.GetResourceLogs() {
			newResourceLogs(es.orig.GetResourceLogs()[i], es.state).CopyTo(newResourceLogs(dest.orig.GetResourceLogs()[i], dest.state))
		}
		return
	}
	origs := make([]otlplogs.ResourceLogs, srcLen)
	wrappers := make([]*otlplogs.ResourceLogs, srcLen)
	for i := range es.orig.GetResourceLogs() {
		wrappers[i] = &origs[i]
		newResourceLogs(es.orig.GetResourceLogs()[i], es.state).CopyTo(newResourceLogs(wrappers[i], dest.state))
	}
	dest.orig.SetResourceLogs(wrappers)
}

// Sort sorts the ResourceLogs elements within ResourceLogsSlice given the
// provided less function so that two instances of ResourceLogsSlice
// can be compared.
func (es ResourceLogsSlice) Sort(less func(a, b ResourceLogs) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetResourceLogs(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
