// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package plog

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlplogs "go.opentelemetry.io/collector/pdata/internal/data/protogen/logs/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ScopeLogsSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type ScopeLogsSliceAccessor interface {
	SetScopeLogs([]*otlplogs.ScopeLogs)
	GetScopeLogs() []*otlplogs.ScopeLogs
}

// ScopeLogsSlice logically represents a slice of ScopeLogs.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewScopeLogsSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ScopeLogsSlice struct {
	orig  ScopeLogsSliceAccessor
	state *internal.State
}

func newScopeLogsSlice(orig ScopeLogsSliceAccessor, state *internal.State) ScopeLogsSlice {
	return ScopeLogsSlice{orig: orig, state: state}
}

// NewScopeLogsSlice creates a ScopeLogsSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewScopeLogsSlice() ScopeLogsSlice {
	state := internal.StateMutable
	return newScopeLogsSlice(&otlplogs.ResourceLogs{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewScopeLogsSlice()".
func (es ScopeLogsSlice) Len() int {
	return len(es.orig.GetScopeLogs())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ScopeLogsSlice) At(i int) ScopeLogs {
	return newScopeLogs(es.orig.GetScopeLogs()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ScopeLogsSlice can be initialized:
//
//	es := NewScopeLogsSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ScopeLogsSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetScopeLogs())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlplogs.ScopeLogs, len(es.orig.GetScopeLogs()), newCap)
	copy(newOrig, es.orig.GetScopeLogs())
	es.orig.SetScopeLogs(newOrig)
}

// AppendEmpty will append to the end of the slice an empty ScopeLogs.
// It returns the newly added ScopeLogs.
func (es ScopeLogsSlice) AppendEmpty() ScopeLogs {
	es.state.AssertMutable()
	es.orig.SetScopeLogs(append(es.orig.GetScopeLogs(), &otlplogs.ScopeLogs{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ScopeLogsSlice) MoveAndAppendTo(dest ScopeLogsSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetScopeLogs() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetScopeLogs(es.orig.GetScopeLogs())
	} else {
		dest.orig.SetScopeLogs(append(dest.orig.GetScopeLogs(), es.orig.GetScopeLogs()...))
	}
	es.orig.SetScopeLogs(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ScopeLogsSlice) RemoveIf(f func(ScopeLogs) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetScopeLogs()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetScopeLogs()[newLen] = es.orig.GetScopeLogs()[i]
		newLen++
	}
	es.orig.SetScopeLogs(es.orig.GetScopeLogs()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ScopeLogsSlice) CopyTo(dest ScopeLogsSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetScopeLogs())
	if srcLen <= destCap {
		dest.orig.SetScopeLogs(dest.orig.GetScopeLogs()[:srcLen:destCap])
		for i := range es.orig.GetScopeLogs() {
			newScopeLogs(es.orig.GetScopeLogs()[i], es.state).CopyTo(newScopeLogs(dest.orig.GetScopeLogs()[i], dest.state))
		}
		return
	}
	origs := make([]otlplogs.ScopeLogs, srcLen)
	wrappers := make([]*otlplogs.ScopeLogs, srcLen)
	for i := range es.orig.GetScopeLogs() {
		wrappers[i] = &origs[i]
		newScopeLogs(es.orig.GetScopeLogs()[i], es.state).CopyTo(newScopeLogs(wrappers[i], dest.state))
	}
	dest.orig.SetScopeLogs(wrappers)
}

// Sort sorts the ScopeLogs elements within ScopeLogsSlice given the
// provided less function so that two instances of ScopeLogsSlice
// can be compared.
func (es ScopeLogsSlice) Sort(less func(a, b ScopeLogs) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetScopeLogs(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
