// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package ptrace

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcollectortrace "go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	otlptrace "go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// SpanSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type SpanSliceAccessor interface {
	SetSpans([]*otlptrace.Span)
	GetSpans() []*otlptrace.Span
}

// SpanSlice logically represents a slice of Span.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewSpanSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type SpanSlice struct {
	orig  SpanSliceAccessor
	state *internal.State
}

func newSpanSlice(orig SpanSliceAccessor, state *internal.State) SpanSlice {
	return SpanSlice{orig: orig, state: state}
}

// NewSpanSlice creates a SpanSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewSpanSlice() SpanSlice {
	state := internal.StateMutable
	return newSpanSlice(&otlptrace.ScopeSpans{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewSpanSlice()".
func (es SpanSlice) Len() int {
	return len(es.orig.GetSpans())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es SpanSlice) At(i int) Span {
	return newSpan(es.orig.GetSpans()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new SpanSlice can be initialized:
//
//	es := NewSpanSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es SpanSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetSpans())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlptrace.Span, len(es.orig.GetSpans()), newCap)
	copy(newOrig, es.orig.GetSpans())
	es.orig.SetSpans(newOrig)
}

// AppendEmpty will append to the end of the slice an empty Span.
// It returns the newly added Span.
func (es SpanSlice) AppendEmpty() Span {
	es.state.AssertMutable()
	es.orig.SetSpans(append(es.orig.GetSpans(), &otlptrace.Span{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es SpanSlice) MoveAndAppendTo(dest SpanSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetSpans() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetSpans(es.orig.GetSpans())
	} else {
		dest.orig.SetSpans(append(dest.orig.GetSpans(), es.orig.GetSpans()...))
	}
	es.orig.SetSpans(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es SpanSlice) RemoveIf(f func(Span) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetSpans()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetSpans()[newLen] = es.orig.GetSpans()[i]
		newLen++
	}
	es.orig.SetSpans(es.orig.GetSpans()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es SpanSlice) CopyTo(dest SpanSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetSpans())
	if srcLen <= destCap {
		dest.orig.SetSpans(dest.orig.GetSpans()[:srcLen:destCap])
		for i := range es.orig.GetSpans() {
			newSpan(es.orig.GetSpans()[i], es.state).CopyTo(newSpan(dest.orig.GetSpans()[i], dest.state))
		}
		return
	}
	origs := make([]otlptrace.Span, srcLen)
	wrappers := make([]*otlptrace.Span, srcLen)
	for i := range es.orig.GetSpans() {
		wrappers[i] = &origs[i]
		newSpan(es.orig.GetSpans()[i], es.state).CopyTo(newSpan(wrappers[i], dest.state))
	}
	dest.orig.SetSpans(wrappers)
}

// Sort sorts the Span elements within SpanSlice given the
// provided less function so that two instances of SpanSlice
// can be compared.
func (es SpanSlice) Sort(less func(a, b Span) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetSpans(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
