// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package ptrace

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	otlptrace "go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1"
)

// SpanEventSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type SpanEventSliceAccessor interface {
	SetEvents([]*otlptrace.Span_Event)
	GetEvents() []*otlptrace.Span_Event
}

// SpanEventSlice logically represents a slice of SpanEvent.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewSpanEventSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type SpanEventSlice struct {
	orig  SpanEventSliceAccessor
	state *internal.State
}

func newSpanEventSlice(orig SpanEventSliceAccessor, state *internal.State) SpanEventSlice {
	return SpanEventSlice{orig: orig, state: state}
}

// NewSpanEventSlice creates a SpanEventSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewSpanEventSlice() SpanEventSlice {
	state := internal.StateMutable
	return newSpanEventSlice(&otlptrace.Span{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewSpanEventSlice()".
func (es SpanEventSlice) Len() int {
	return len(es.orig.GetEvents())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es SpanEventSlice) At(i int) SpanEvent {
	return newSpanEvent(es.orig.GetEvents()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new SpanEventSlice can be initialized:
//
//	es := NewSpanEventSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es SpanEventSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetEvents())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlptrace.Span_Event, len(es.orig.GetEvents()), newCap)
	copy(newOrig, es.orig.GetEvents())
	es.orig.SetEvents(newOrig)
}

// AppendEmpty will append to the end of the slice an empty SpanEvent.
// It returns the newly added SpanEvent.
func (es SpanEventSlice) AppendEmpty() SpanEvent {
	es.state.AssertMutable()
	es.orig.SetEvents(append(es.orig.GetEvents(), &otlptrace.Span_Event{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es SpanEventSlice) MoveAndAppendTo(dest SpanEventSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetEvents() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetEvents(es.orig.GetEvents())
	} else {
		dest.orig.SetEvents(append(dest.orig.GetEvents(), es.orig.GetEvents()...))
	}
	es.orig.SetEvents(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es SpanEventSlice) RemoveIf(f func(SpanEvent) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetEvents()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetEvents()[newLen] = es.orig.GetEvents()[i]
		newLen++
	}
	es.orig.SetEvents(es.orig.GetEvents()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es SpanEventSlice) CopyTo(dest SpanEventSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetEvents())
	if srcLen <= destCap {
		dest.orig.SetEvents(dest.orig.GetEvents()[:srcLen:destCap])
		for i := range es.orig.GetEvents() {
			newSpanEvent(es.orig.GetEvents()[i], es.state).CopyTo(newSpanEvent(dest.orig.GetEvents()[i], dest.state))
		}
		return
	}
	origs := make([]otlptrace.Span_Event, srcLen)
	wrappers := make([]*otlptrace.Span_Event, srcLen)
	for i := range es.orig.GetEvents() {
		wrappers[i] = &origs[i]
		newSpanEvent(es.orig.GetEvents()[i], es.state).CopyTo(newSpanEvent(wrappers[i], dest.state))
	}
	dest.orig.SetEvents(wrappers)
}

// Sort sorts the SpanEvent elements within SpanEventSlice given the
// provided less function so that two instances of SpanEventSlice
// can be compared.
func (es SpanEventSlice) Sort(less func(a, b SpanEvent) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetEvents(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
