// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pprofile

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
)

// ValueTypeSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type ValueTypeSliceAccessor interface {
	SetPeriodType([]*otlpprofiles.ValueType)
	GetPeriodType() []*otlpprofiles.ValueType
}

// ValueTypeSlice logically represents a slice of ValueType.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewValueTypeSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ValueTypeSlice struct {
	orig  ValueTypeSliceAccessor
	state *internal.State
}

func newValueTypeSlice(orig ValueTypeSliceAccessor, state *internal.State) ValueTypeSlice {
	return ValueTypeSlice{orig: orig, state: state}
}

// NewValueTypeSlice creates a ValueTypeSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewValueTypeSlice() ValueTypeSlice {
	state := internal.StateMutable
	return newValueTypeSlice(&otlpprofiles.Profile{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewValueTypeSlice()".
func (es ValueTypeSlice) Len() int {
	return len(es.orig.GetPeriodType())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ValueTypeSlice) At(i int) ValueType {
	return newValueType(es.orig.GetPeriodType()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ValueTypeSlice can be initialized:
//
//	es := NewValueTypeSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ValueTypeSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetPeriodType())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpprofiles.ValueType, len(es.orig.GetPeriodType()), newCap)
	copy(newOrig, es.orig.GetPeriodType())
	es.orig.SetPeriodType(newOrig)
}

// AppendEmpty will append to the end of the slice an empty ValueType.
// It returns the newly added ValueType.
func (es ValueTypeSlice) AppendEmpty() ValueType {
	es.state.AssertMutable()
	es.orig.SetPeriodType(append(es.orig.GetPeriodType(), &otlpprofiles.ValueType{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ValueTypeSlice) MoveAndAppendTo(dest ValueTypeSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetPeriodType() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetPeriodType(es.orig.GetPeriodType())
	} else {
		dest.orig.SetPeriodType(append(dest.orig.GetPeriodType(), es.orig.GetPeriodType()...))
	}
	es.orig.SetPeriodType(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ValueTypeSlice) RemoveIf(f func(ValueType) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetPeriodType()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetPeriodType()[newLen] = es.orig.GetPeriodType()[i]
		newLen++
	}
	es.orig.SetPeriodType(es.orig.GetPeriodType()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ValueTypeSlice) CopyTo(dest ValueTypeSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetPeriodType())
	if srcLen <= destCap {
		dest.orig.SetPeriodType(dest.orig.GetPeriodType()[:srcLen:destCap])
		for i := range es.orig.GetPeriodType() {
			newValueType(es.orig.GetPeriodType()[i], es.state).CopyTo(newValueType(dest.orig.GetPeriodType()[i], dest.state))
		}
		return
	}
	origs := make([]otlpprofiles.ValueType, srcLen)
	wrappers := make([]*otlpprofiles.ValueType, srcLen)
	for i := range es.orig.GetPeriodType() {
		wrappers[i] = &origs[i]
		newValueType(es.orig.GetPeriodType()[i], es.state).CopyTo(newValueType(wrappers[i], dest.state))
	}
	dest.orig.SetPeriodType(wrappers)
}

// Sort sorts the ValueType elements within ValueTypeSlice given the
// provided less function so that two instances of ValueTypeSlice
// can be compared.
func (es ValueTypeSlice) Sort(less func(a, b ValueType) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetPeriodType(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
