// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// LinkSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type LinkSliceAccessor interface {
	SetLinkTable([]*otlpprofiles.Link)
	GetLinkTable() []*otlpprofiles.Link
}

// LinkSlice logically represents a slice of Link.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewLinkSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type LinkSlice struct {
	orig  LinkSliceAccessor
	state *internal.State
}

func newLinkSlice(orig LinkSliceAccessor, state *internal.State) LinkSlice {
	return LinkSlice{orig: orig, state: state}
}

// NewLinkSlice creates a LinkSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewLinkSlice() LinkSlice {
	state := internal.StateMutable
	return newLinkSlice(&otlpprofile.Profile{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewLinkSlice()".
func (es LinkSlice) Len() int {
	return len(es.orig.GetLinkTable())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es LinkSlice) At(i int) Link {
	return newLink(es.orig.GetLinkTable()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new LinkSlice can be initialized:
//
//	es := NewLinkSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es LinkSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetLinkTable())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpprofiles.Link, len(es.orig.GetLinkTable()), newCap)
	copy(newOrig, es.orig.GetLinkTable())
	es.orig.SetLinkTable(newOrig)
}

// AppendEmpty will append to the end of the slice an empty Link.
// It returns the newly added Link.
func (es LinkSlice) AppendEmpty() Link {
	es.state.AssertMutable()
	es.orig.SetLinkTable(append(es.orig.GetLinkTable(), &otlpprofiles.Link{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es LinkSlice) MoveAndAppendTo(dest LinkSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetLinkTable() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetLinkTable(es.orig.GetLinkTable())
	} else {
		dest.orig.SetLinkTable(append(dest.orig.GetLinkTable(), es.orig.GetLinkTable()...))
	}
	es.orig.SetLinkTable(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es LinkSlice) RemoveIf(f func(Link) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetLinkTable()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetLinkTable()[newLen] = es.orig.GetLinkTable()[i]
		newLen++
	}
	es.orig.SetLinkTable(es.orig.GetLinkTable()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es LinkSlice) CopyTo(dest LinkSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetLinkTable())
	if srcLen <= destCap {
		dest.orig.SetLinkTable(dest.orig.GetLinkTable()[:srcLen:destCap])
		for i := range es.orig.GetLinkTable() {
			newLink(es.orig.GetLinkTable()[i], es.state).CopyTo(newLink(dest.orig.GetLinkTable()[i], dest.state))
		}
		return
	}
	origs := make([]otlpprofiles.Link, srcLen)
	wrappers := make([]*otlpprofiles.Link, srcLen)
	for i := range es.orig.GetLinkTable() {
		wrappers[i] = &origs[i]
		newLink(es.orig.GetLinkTable()[i], es.state).CopyTo(newLink(wrappers[i], dest.state))
	}
	dest.orig.SetLinkTable(wrappers)
}

// Sort sorts the Link elements within LinkSlice given the
// provided less function so that two instances of LinkSlice
// can be compared.
func (es LinkSlice) Sort(less func(a, b Link) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetLinkTable(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
