// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// LocationSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type LocationSliceAccessor interface {
	SetLocationTable([]*otlpprofiles.Location)
	GetLocationTable() []*otlpprofiles.Location
}

// LocationSlice logically represents a slice of Location.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewLocationSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type LocationSlice struct {
	orig  LocationSliceAccessor
	state *internal.State
}

func newLocationSlice(orig LocationSliceAccessor, state *internal.State) LocationSlice {
	return LocationSlice{orig: orig, state: state}
}

// NewLocationSlice creates a LocationSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewLocationSlice() LocationSlice {
	state := internal.StateMutable
	return newLocationSlice(&otlpprofiles.Profile{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewLocationSlice()".
func (es LocationSlice) Len() int {
	return len(es.orig.GetLocationTable())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es LocationSlice) At(i int) Location {
	return newLocation(es.orig.GetLocationTable()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new LocationSlice can be initialized:
//
//	es := NewLocationSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es LocationSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetLocationTable())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpprofiles.Location, len(es.orig.GetLocationTable()), newCap)
	copy(newOrig, es.orig.GetLocationTable())
	es.orig.SetLocationTable(newOrig)
}

// AppendEmpty will append to the end of the slice an empty Location.
// It returns the newly added Location.
func (es LocationSlice) AppendEmpty() Location {
	es.state.AssertMutable()
	es.orig.SetLocationTable(append(es.orig.GetLocationTable(), &otlpprofiles.Location{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es LocationSlice) MoveAndAppendTo(dest LocationSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetLocationTable() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetLocationTable(es.orig.GetLocationTable())
	} else {
		dest.orig.SetLocationTable(append(dest.orig.GetLocationTable(), es.orig.GetLocationTable()...))
	}
	es.orig.SetLocationTable(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es LocationSlice) RemoveIf(f func(Location) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetLocationTable()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetLocationTable()[newLen] = es.orig.GetLocationTable()[i]
		newLen++
	}
	es.orig.SetLocationTable(es.orig.GetLocationTable()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es LocationSlice) CopyTo(dest LocationSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetLocationTable())
	if srcLen <= destCap {
		dest.orig.SetLocationTable(dest.orig.GetLocationTable()[:srcLen:destCap])
		for i := range es.orig.GetLocationTable() {
			newLocation(es.orig.GetLocationTable()[i], es.state).CopyTo(newLocation(dest.orig.GetLocationTable()[i], dest.state))
		}
		return
	}
	origs := make([]otlpprofiles.Location, srcLen)
	wrappers := make([]*otlpprofiles.Location, srcLen)
	for i := range es.orig.GetLocationTable() {
		wrappers[i] = &origs[i]
		newLocation(es.orig.GetLocationTable()[i], es.state).CopyTo(newLocation(wrappers[i], dest.state))
	}
	dest.orig.SetLocationTable(wrappers)
}

// Sort sorts the Location elements within LocationSlice given the
// provided less function so that two instances of LocationSlice
// can be compared.
func (es LocationSlice) Sort(less func(a, b Location) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetLocationTable(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
