// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message.go.tmpl

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pcommon/utils"
)

// ResourceProfiles is a collection of profiles from a Resource.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewResourceProfiles function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ResourceProfiles struct {
	orig  *otlpprofiles.ResourceProfiles
	state *internal.State
}

func newResourceProfiles(orig *otlpprofiles.ResourceProfiles, state *internal.State) ResourceProfiles {
	return ResourceProfiles{orig: orig, state: state}
}

// NewResourceProfiles creates a new empty ResourceProfiles.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewResourceProfiles() ResourceProfiles {
	state := internal.StateMutable
	return newResourceProfiles(otlpprofiles.ResourceProfiles_builder{}.Build(), &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ResourceProfiles) MoveTo(dest ResourceProfiles) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	*dest.orig = *ms.orig
	*ms.orig = otlpprofiles.ResourceProfiles{}
}

// Resource returns the resource associated with this ResourceProfiles.
// accessorsMessageValueTemplate
func (ms ResourceProfiles) Resource() pcommon.Resource {
	if !ms.orig.HasResource() {
		ms.orig.SetResource(&otlpresource.Resource{})
	}
	return pcommon.Resource(internal.NewResource(ms.orig.GetResource(), ms.state))
}

// SchemaUrl returns the schemaurl associated with this ResourceProfiles.
// accessorsPrimitiveTemplate
func (ms ResourceProfiles) SchemaUrl() string {
	return ms.orig.GetSchemaUrl()
}

// SetSchemaUrl replaces the schemaurl associated with this ResourceProfiles.
func (ms ResourceProfiles) SetSchemaUrl(v string) {
	ms.state.AssertMutable()
	ms.orig.SetSchemaUrl(v)
}

// ScopeProfiles returns the ScopeProfiles associated with this ResourceProfiles.
// accessorSliceTemplate
func (ms ResourceProfiles) ScopeProfiles() ScopeProfilesSlice {
	if ms.orig.GetScopeProfiles() == nil {
		ms.orig.SetScopeProfiles(utils.GetEmptyPointer(ms.orig.GetScopeProfiles()))
	}
	sl := ms.orig.GetScopeProfiles()
	return newScopeProfilesSlice(&sl, ms.state)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ResourceProfiles) CopyTo(dest ResourceProfiles) {
	dest.state.AssertMutable()
	ms.Resource().CopyTo(dest.Resource())
	dest.SetSchemaUrl(ms.SchemaUrl())
	ms.ScopeProfiles().CopyTo(dest.ScopeProfiles())
}
