// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pprofile

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	otlpprofile "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
)

// LineSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type LineSliceAccessor interface {
	SetLine([]*otlpprofiles.Line)
	GetLine() []*otlpprofiles.Line
}

// LineSlice logically represents a slice of Line.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewLineSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type LineSlice struct {
	orig  LineSliceAccessor
	state *internal.State
}

func newLineSlice(orig LineSliceAccessor, state *internal.State) LineSlice {
	return LineSlice{orig: orig, state: state}
}

// NewLineSlice creates a LineSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewLineSlice() LineSlice {
	state := internal.StateMutable
	return newLineSlice(&otlpprofile.Location{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewLineSlice()".
func (es LineSlice) Len() int {
	return len(es.orig.GetLine())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es LineSlice) At(i int) Line {
	return newLine(es.orig.GetLine()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new LineSlice can be initialized:
//
//	es := NewLineSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es LineSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetLine())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpprofiles.Line, len(es.orig.GetLine()), newCap)
	copy(newOrig, es.orig.GetLine())
	es.orig.SetLine(newOrig)
}

// AppendEmpty will append to the end of the slice an empty Line.
// It returns the newly added Line.
func (es LineSlice) AppendEmpty() Line {
	es.state.AssertMutable()
	es.orig.SetLine(append(es.orig.GetLine(), &otlpprofiles.Line{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es LineSlice) MoveAndAppendTo(dest LineSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetLine() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetLine(es.orig.GetLine())
	} else {
		dest.orig.SetLine(append(dest.orig.GetLine(), es.orig.GetLine()...))
	}
	es.orig.SetLine(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es LineSlice) RemoveIf(f func(Line) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetLine()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetLine()[newLen] = es.orig.GetLine()[i]
		newLen++
	}
	es.orig.SetLine(es.orig.GetLine()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es LineSlice) CopyTo(dest LineSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetLine())
	if srcLen <= destCap {
		dest.orig.SetLine(dest.orig.GetLine()[:srcLen:destCap])
		for i := range es.orig.GetLine() {
			newLine(es.orig.GetLine()[i], es.state).CopyTo(newLine(dest.orig.GetLine()[i], dest.state))
		}
		return
	}
	origs := make([]otlpprofiles.Line, srcLen)
	wrappers := make([]*otlpprofiles.Line, srcLen)
	for i := range es.orig.GetLine() {
		wrappers[i] = &origs[i]
		newLine(es.orig.GetLine()[i], es.state).CopyTo(newLine(wrappers[i], dest.state))
	}
	dest.orig.SetLine(wrappers)
}

// Sort sorts the Line elements within LineSlice given the
// provided less function so that two instances of LineSlice
// can be compared.
func (es LineSlice) Sort(less func(a, b Line) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetLine(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
