// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pprofile

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
)

// ResourceProfilesSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type ResourceProfilesSliceAccessor interface {
	SetResourceProfiles([]*otlpprofiles.ResourceProfiles)
	GetResourceProfiles() []*otlpprofiles.ResourceProfiles
}

// ResourceProfilesSlice logically represents a slice of ResourceProfiles.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewResourceProfilesSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ResourceProfilesSlice struct {
	orig  ResourceProfilesSliceAccessor
	state *internal.State
}

func newResourceProfilesSlice(orig ResourceProfilesSliceAccessor, state *internal.State) ResourceProfilesSlice {
	return ResourceProfilesSlice{orig: orig, state: state}
}

// NewResourceProfilesSlice creates a ResourceProfilesSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewResourceProfilesSlice() ResourceProfilesSlice {
	state := internal.StateMutable
	return newResourceProfilesSlice(&otlpprofiles.ExportProfileServiceRequest{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewResourceProfilesSlice()".
func (es ResourceProfilesSlice) Len() int {
	return len(es.orig.GetResourceProfiles())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ResourceProfilesSlice) At(i int) ResourceProfiles {
	return newResourceProfiles(es.orig.GetResourceProfiles()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ResourceProfilesSlice can be initialized:
//
//	es := NewResourceProfilesSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ResourceProfilesSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetResourceProfiles())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpprofiles.ResourceProfiles, len(es.orig.GetResourceProfiles()), newCap)
	copy(newOrig, es.orig.GetResourceProfiles())
	es.orig.SetResourceProfiles(newOrig)
}

// AppendEmpty will append to the end of the slice an empty ResourceProfiles.
// It returns the newly added ResourceProfiles.
func (es ResourceProfilesSlice) AppendEmpty() ResourceProfiles {
	es.state.AssertMutable()
	es.orig.SetResourceProfiles(append(es.orig.GetResourceProfiles(), &otlpprofiles.ResourceProfiles{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ResourceProfilesSlice) MoveAndAppendTo(dest ResourceProfilesSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetResourceProfiles() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetResourceProfiles(es.orig.GetResourceProfiles())
	} else {
		dest.orig.SetResourceProfiles(append(dest.orig.GetResourceProfiles(), es.orig.GetResourceProfiles()...))
	}
	es.orig.SetResourceProfiles(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ResourceProfilesSlice) RemoveIf(f func(ResourceProfiles) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetResourceProfiles()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetResourceProfiles()[newLen] = es.orig.GetResourceProfiles()[i]
		newLen++
	}
	es.orig.SetResourceProfiles(es.orig.GetResourceProfiles()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ResourceProfilesSlice) CopyTo(dest ResourceProfilesSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetResourceProfiles())
	if srcLen <= destCap {
		dest.orig.SetResourceProfiles(dest.orig.GetResourceProfiles()[:srcLen:destCap])
		for i := range es.orig.GetResourceProfiles() {
			newResourceProfiles(es.orig.GetResourceProfiles()[i], es.state).CopyTo(newResourceProfiles(dest.orig.GetResourceProfiles()[i], dest.state))
		}
		return
	}
	origs := make([]otlpprofiles.ResourceProfiles, srcLen)
	wrappers := make([]*otlpprofiles.ResourceProfiles, srcLen)
	for i := range es.orig.GetResourceProfiles() {
		wrappers[i] = &origs[i]
		newResourceProfiles(es.orig.GetResourceProfiles()[i], es.state).CopyTo(newResourceProfiles(wrappers[i], dest.state))
	}
	dest.orig.SetResourceProfiles(wrappers)
}

// Sort sorts the ResourceProfiles elements within ResourceProfilesSlice given the
// provided less function so that two instances of ResourceProfilesSlice
// can be compared.
func (es ResourceProfilesSlice) Sort(less func(a, b ResourceProfiles) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetResourceProfiles(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
