// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message.go.tmpl

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ScopeProfiles is a collection of profiles from a LibraryInstrumentation.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewScopeProfiles function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ScopeProfiles struct {
	orig  *otlpprofiles.ScopeProfiles
	state *internal.State
}

func newScopeProfiles(orig *otlpprofiles.ScopeProfiles, state *internal.State) ScopeProfiles {
	return ScopeProfiles{orig: orig, state: state}
}

// NewScopeProfiles creates a new empty ScopeProfiles.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewScopeProfiles() ScopeProfiles {
	state := internal.StateMutable
	return newScopeProfiles(otlpprofiles.ScopeProfiles_builder{}.Build(), &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ScopeProfiles) MoveTo(dest ScopeProfiles) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	*dest.orig = *ms.orig
	*ms.orig = otlpprofiles.ScopeProfiles{}
}

// Scope returns the scope associated with this ScopeProfiles.
// accessorsMessageValueTemplate
func (ms ScopeProfiles) Scope() pcommon.InstrumentationScope {
	if !ms.orig.HasScope() {
		ms.orig.SetScope(&otlpcommon.InstrumentationScope{})
	}
	return pcommon.InstrumentationScope(internal.NewInstrumentationScope(ms.orig.GetScope(), ms.state))
}

// SchemaUrl returns the schemaurl associated with this ScopeProfiles.
// accessorsPrimitiveTemplate
func (ms ScopeProfiles) SchemaUrl() string {
	return ms.orig.GetSchemaUrl()
}

// SetSchemaUrl replaces the schemaurl associated with this ScopeProfiles.
func (ms ScopeProfiles) SetSchemaUrl(v string) {
	ms.state.AssertMutable()
	ms.orig.SetSchemaUrl(v)
}

// Profiles returns the Profiles associated with this ScopeProfiles.
// accessorSliceTemplate
func (ms ScopeProfiles) Profiles() ProfilesSlice {
	return newProfilesSlice(ms.orig, ms.state)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ScopeProfiles) CopyTo(dest ScopeProfiles) {
	dest.state.AssertMutable()
	ms.Scope().CopyTo(dest.Scope())
	dest.SetSchemaUrl(ms.SchemaUrl())
	ms.Profiles().CopyTo(dest.Profiles())
}
