// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// FunctionSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type FunctionSliceAccessor interface {
	SetFunctionTable([]*otlpprofiles.Function)
	GetFunctionTable() []*otlpprofiles.Function
}

// FunctionSlice logically represents a slice of Function.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewFunctionSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type FunctionSlice struct {
	orig  FunctionSliceAccessor
	state *internal.State
}

func newFunctionSlice(orig FunctionSliceAccessor, state *internal.State) FunctionSlice {
	return FunctionSlice{orig: orig, state: state}
}

// NewFunctionSlice creates a FunctionSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewFunctionSlice() FunctionSlice {
	state := internal.StateMutable
	return newFunctionSlice(&otlpprofiles.Profile{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewFunctionSlice()".
func (es FunctionSlice) Len() int {
	return len(es.orig.GetFunctionTable())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es FunctionSlice) At(i int) Function {
	return newFunction(es.orig.GetFunctionTable()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new FunctionSlice can be initialized:
//
//	es := NewFunctionSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es FunctionSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetFunctionTable())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpprofiles.Function, len(es.orig.GetFunctionTable()), newCap)
	copy(newOrig, es.orig.GetFunctionTable())
	es.orig.SetFunctionTable(newOrig)
}

// AppendEmpty will append to the end of the slice an empty Function.
// It returns the newly added Function.
func (es FunctionSlice) AppendEmpty() Function {
	es.state.AssertMutable()
	es.orig.SetFunctionTable(append(es.orig.GetFunctionTable(), &otlpprofiles.Function{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es FunctionSlice) MoveAndAppendTo(dest FunctionSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetFunctionTable() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetFunctionTable(es.orig.GetFunctionTable())
	} else {
		dest.orig.SetFunctionTable(append(dest.orig.GetFunctionTable(), es.orig.GetFunctionTable()...))
	}
	es.orig.SetFunctionTable(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es FunctionSlice) RemoveIf(f func(Function) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetFunctionTable()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetFunctionTable()[newLen] = es.orig.GetFunctionTable()[i]
		newLen++
	}
	es.orig.SetFunctionTable(es.orig.GetFunctionTable()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es FunctionSlice) CopyTo(dest FunctionSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetFunctionTable())
	if srcLen <= destCap {
		dest.orig.SetFunctionTable(dest.orig.GetFunctionTable()[:srcLen:destCap])
		for i := range es.orig.GetFunctionTable() {
			newFunction(es.orig.GetFunctionTable()[i], es.state).CopyTo(newFunction(dest.orig.GetFunctionTable()[i], dest.state))
		}
		return
	}
	origs := make([]otlpprofiles.Function, srcLen)
	wrappers := make([]*otlpprofiles.Function, srcLen)
	for i := range es.orig.GetFunctionTable() {
		wrappers[i] = &origs[i]
		newFunction(es.orig.GetFunctionTable()[i], es.state).CopyTo(newFunction(wrappers[i], dest.state))
	}
	dest.orig.SetFunctionTable(wrappers)
}

// Sort sorts the Function elements within FunctionSlice given the
// provided less function so that two instances of FunctionSlice
// can be compared.
func (es FunctionSlice) Sort(less func(a, b Function) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetFunctionTable(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
