// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pprofile

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
)

// SampleSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type SampleSliceAccessor interface {
	SetSample([]*otlpprofiles.Sample)
	GetSample() []*otlpprofiles.Sample
}

// SampleSlice logically represents a slice of Sample.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewSampleSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type SampleSlice struct {
	orig  SampleSliceAccessor
	state *internal.State
}

func newSampleSlice(orig SampleSliceAccessor, state *internal.State) SampleSlice {
	return SampleSlice{orig: orig, state: state}
}

// NewSampleSlice creates a SampleSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewSampleSlice() SampleSlice {
	state := internal.StateMutable
	return newSampleSlice(&otlpprofiles.Profile{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewSampleSlice()".
func (es SampleSlice) Len() int {
	return len(es.orig.GetSample())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es SampleSlice) At(i int) Sample {
	return newSample(es.orig.GetSample()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new SampleSlice can be initialized:
//
//	es := NewSampleSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es SampleSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetSample())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpprofiles.Sample, len(es.orig.GetSample()), newCap)
	copy(newOrig, es.orig.GetSample())
	es.orig.SetSample(newOrig)
}

// AppendEmpty will append to the end of the slice an empty Sample.
// It returns the newly added Sample.
func (es SampleSlice) AppendEmpty() Sample {
	es.state.AssertMutable()
	es.orig.SetSample(append(es.orig.GetSample(), &otlpprofiles.Sample{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es SampleSlice) MoveAndAppendTo(dest SampleSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetSample() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetSample(es.orig.GetSample())
	} else {
		dest.orig.SetSample(append(dest.orig.GetSample(), es.orig.GetSample()...))
	}
	es.orig.SetSample(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es SampleSlice) RemoveIf(f func(Sample) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetSample()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetSample()[newLen] = es.orig.GetSample()[i]
		newLen++
	}
	es.orig.SetSample(es.orig.GetSample()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es SampleSlice) CopyTo(dest SampleSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetSample())
	if srcLen <= destCap {
		dest.orig.SetSample(dest.orig.GetSample()[:srcLen:destCap])
		for i := range es.orig.GetSample() {
			newSample(es.orig.GetSample()[i], es.state).CopyTo(newSample(dest.orig.GetSample()[i], dest.state))
		}
		return
	}
	origs := make([]otlpprofiles.Sample, srcLen)
	wrappers := make([]*otlpprofiles.Sample, srcLen)
	for i := range es.orig.GetSample() {
		wrappers[i] = &origs[i]
		newSample(es.orig.GetSample()[i], es.state).CopyTo(newSample(wrappers[i], dest.state))
	}
	dest.orig.SetSample(wrappers)
}

// Sort sorts the Sample elements within SampleSlice given the
// provided less function so that two instances of SampleSlice
// can be compared.
func (es SampleSlice) Sort(less func(a, b Sample) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetSample(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
