// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pmetric

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// SummaryDataPointSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type SummaryDataPointSliceAccessor interface {
	SetDataPoints([]*otlpmetrics.SummaryDataPoint)
	GetDataPoints() []*otlpmetrics.SummaryDataPoint
}

// SummaryDataPointSlice logically represents a slice of SummaryDataPoint.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewSummaryDataPointSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type SummaryDataPointSlice struct {
	orig  SummaryDataPointSliceAccessor
	state *internal.State
}

func newSummaryDataPointSlice(orig SummaryDataPointSliceAccessor, state *internal.State) SummaryDataPointSlice {
	return SummaryDataPointSlice{orig: orig, state: state}
}

// NewSummaryDataPointSlice creates a SummaryDataPointSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewSummaryDataPointSlice() SummaryDataPointSlice {
	state := internal.StateMutable
	return newSummaryDataPointSlice(&otlpmetrics.Summary{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewSummaryDataPointSlice()".
func (es SummaryDataPointSlice) Len() int {
	return len(es.orig.GetDataPoints())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es SummaryDataPointSlice) At(i int) SummaryDataPoint {
	return newSummaryDataPoint(es.orig.GetDataPoints()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new SummaryDataPointSlice can be initialized:
//
//	es := NewSummaryDataPointSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es SummaryDataPointSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetDataPoints())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpmetrics.SummaryDataPoint, len(es.orig.GetDataPoints()), newCap)
	copy(newOrig, es.orig.GetDataPoints())
	es.orig.SetDataPoints(newOrig)
}

// AppendEmpty will append to the end of the slice an empty SummaryDataPoint.
// It returns the newly added SummaryDataPoint.
func (es SummaryDataPointSlice) AppendEmpty() SummaryDataPoint {
	es.state.AssertMutable()
	es.orig.SetDataPoints(append(es.orig.GetDataPoints(), &otlpmetrics.SummaryDataPoint{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es SummaryDataPointSlice) MoveAndAppendTo(dest SummaryDataPointSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetDataPoints() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetDataPoints(es.orig.GetDataPoints())
	} else {
		dest.orig.SetDataPoints(append(dest.orig.GetDataPoints(), es.orig.GetDataPoints()...))
	}
	es.orig.SetDataPoints(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es SummaryDataPointSlice) RemoveIf(f func(SummaryDataPoint) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetDataPoints()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetDataPoints()[newLen] = es.orig.GetDataPoints()[i]
		newLen++
	}
	es.orig.SetDataPoints(es.orig.GetDataPoints()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es SummaryDataPointSlice) CopyTo(dest SummaryDataPointSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetDataPoints())
	if srcLen <= destCap {
		dest.orig.SetDataPoints(dest.orig.GetDataPoints()[:srcLen:destCap])
		for i := range es.orig.GetDataPoints() {
			newSummaryDataPoint(es.orig.GetDataPoints()[i], es.state).CopyTo(newSummaryDataPoint(dest.orig.GetDataPoints()[i], dest.state))
		}
		return
	}
	origs := make([]otlpmetrics.SummaryDataPoint, srcLen)
	wrappers := make([]*otlpmetrics.SummaryDataPoint, srcLen)
	for i := range es.orig.GetDataPoints() {
		wrappers[i] = &origs[i]
		newSummaryDataPoint(es.orig.GetDataPoints()[i], es.state).CopyTo(newSummaryDataPoint(wrappers[i], dest.state))
	}
	dest.orig.SetDataPoints(wrappers)
}

// Sort sorts the SummaryDataPoint elements within SummaryDataPointSlice given the
// provided less function so that two instances of SummaryDataPointSlice
// can be compared.
func (es SummaryDataPointSlice) Sort(less func(a, b SummaryDataPoint) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetDataPoints(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
