// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message.go.tmpl

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pcommon/utils"
)

// ResourceMetrics is a collection of metrics from a Resource.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewResourceMetrics function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ResourceMetrics struct {
	orig  *otlpmetrics.ResourceMetrics
	state *internal.State
}

func newResourceMetrics(orig *otlpmetrics.ResourceMetrics, state *internal.State) ResourceMetrics {
	return ResourceMetrics{orig: orig, state: state}
}

// NewResourceMetrics creates a new empty ResourceMetrics.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewResourceMetrics() ResourceMetrics {
	state := internal.StateMutable
	return newResourceMetrics(otlpmetrics.ResourceMetrics_builder{}.Build(), &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ResourceMetrics) MoveTo(dest ResourceMetrics) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	*dest.orig = *ms.orig
	*ms.orig = otlpmetrics.ResourceMetrics{}
}

// Resource returns the resource associated with this ResourceMetrics.
// accessorsMessageValueTemplate
func (ms ResourceMetrics) Resource() pcommon.Resource {
	if !ms.orig.HasResource() {
		ms.orig.SetResource(&otlpresource.Resource{})
	}
	return pcommon.Resource(internal.NewResource(ms.orig.GetResource(), ms.state))
}

// SchemaUrl returns the schemaurl associated with this ResourceMetrics.
// accessorsPrimitiveTemplate
func (ms ResourceMetrics) SchemaUrl() string {
	return ms.orig.GetSchemaUrl()
}

// SetSchemaUrl replaces the schemaurl associated with this ResourceMetrics.
func (ms ResourceMetrics) SetSchemaUrl(v string) {
	ms.state.AssertMutable()
	ms.orig.SetSchemaUrl(v)
}

// ScopeMetrics returns the ScopeMetrics associated with this ResourceMetrics.
// accessorSliceTemplate
func (ms ResourceMetrics) ScopeMetrics() ScopeMetricsSlice {
	if ms.orig.GetScopeMetrics() == nil {
		ms.orig.SetScopeMetrics(utils.GetEmptyPointer(ms.orig.GetScopeMetrics()))
	}
	sl := ms.orig.GetScopeMetrics()
	return newScopeMetricsSlice(&sl, ms.state)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ResourceMetrics) CopyTo(dest ResourceMetrics) {
	dest.state.AssertMutable()
	ms.Resource().CopyTo(dest.Resource())
	dest.SetSchemaUrl(ms.SchemaUrl())
	ms.ScopeMetrics().CopyTo(dest.ScopeMetrics())
}
