// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pmetric

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// HistogramDataPointSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type HistogramDataPointSliceAccessor interface {
	SetHistogramDataPoints([]*otlpmetrics.HistogramDataPoint)
	GetHistogramDataPoints() []*otlpmetrics.HistogramDataPoint
}

// HistogramDataPointSlice logically represents a slice of HistogramDataPoint.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewHistogramDataPointSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type HistogramDataPointSlice struct {
	orig  HistogramDataPointSliceAccessor
	state *internal.State
}

func newHistogramDataPointSlice(orig HistogramDataPointSliceAccessor, state *internal.State) HistogramDataPointSlice {
	return HistogramDataPointSlice{orig: orig, state: state}
}

// NewHistogramDataPointSlice creates a HistogramDataPointSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewHistogramDataPointSlice() HistogramDataPointSlice {
	state := internal.StateMutable
	return newHistogramDataPointSlice(&otlpmetric.Histogram{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewHistogramDataPointSlice()".
func (es HistogramDataPointSlice) Len() int {
	return len(es.orig.GetHistogramDataPoints())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es HistogramDataPointSlice) At(i int) HistogramDataPoint {
	return newHistogramDataPoint(es.orig.GetHistogramDataPoints()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new HistogramDataPointSlice can be initialized:
//
//	es := NewHistogramDataPointSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es HistogramDataPointSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetHistogramDataPoints())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpmetrics.HistogramDataPoint, len(es.orig.GetHistogramDataPoints()), newCap)
	copy(newOrig, es.orig.GetHistogramDataPoints())
	es.orig.SetHistogramDataPoints(newOrig)
}

// AppendEmpty will append to the end of the slice an empty HistogramDataPoint.
// It returns the newly added HistogramDataPoint.
func (es HistogramDataPointSlice) AppendEmpty() HistogramDataPoint {
	es.state.AssertMutable()
	es.orig.SetHistogramDataPoints(append(es.orig.GetHistogramDataPoints(), &otlpmetrics.HistogramDataPoint{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es HistogramDataPointSlice) MoveAndAppendTo(dest HistogramDataPointSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetHistogramDataPoints() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetHistogramDataPoints(es.orig.GetHistogramDataPoints())
	} else {
		dest.orig.SetHistogramDataPoints(append(dest.orig.GetHistogramDataPoints(), es.orig.GetHistogramDataPoints()...))
	}
	es.orig.SetHistogramDataPoints(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es HistogramDataPointSlice) RemoveIf(f func(HistogramDataPoint) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetHistogramDataPoints()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetHistogramDataPoints()[newLen] = es.orig.GetHistogramDataPoints()[i]
		newLen++
	}
	es.orig.SetHistogramDataPoints(es.orig.GetHistogramDataPoints()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es HistogramDataPointSlice) CopyTo(dest HistogramDataPointSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetHistogramDataPoints())
	if srcLen <= destCap {
		dest.orig.SetHistogramDataPoints(dest.orig.GetHistogramDataPoints()[:srcLen:destCap])
		for i := range es.orig.GetHistogramDataPoints() {
			newHistogramDataPoint(es.orig.GetHistogramDataPoints()[i], es.state).CopyTo(newHistogramDataPoint(dest.orig.GetHistogramDataPoints()[i], dest.state))
		}
		return
	}
	origs := make([]otlpmetrics.HistogramDataPoint, srcLen)
	wrappers := make([]*otlpmetrics.HistogramDataPoint, srcLen)
	for i := range es.orig.GetHistogramDataPoints() {
		wrappers[i] = &origs[i]
		newHistogramDataPoint(es.orig.GetHistogramDataPoints()[i], es.state).CopyTo(newHistogramDataPoint(wrappers[i], dest.state))
	}
	dest.orig.SetHistogramDataPoints(wrappers)
}

// Sort sorts the HistogramDataPoint elements within HistogramDataPointSlice given the
// provided less function so that two instances of HistogramDataPointSlice
// can be compared.
func (es HistogramDataPointSlice) Sort(less func(a, b HistogramDataPoint) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetHistogramDataPoints(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
