// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message.go.tmpl

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pcommon/utils"
)

// ScopeMetrics is a collection of metrics from a LibraryInstrumentation.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewScopeMetrics function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ScopeMetrics struct {
	orig  *otlpmetrics.ScopeMetrics
	state *internal.State
}

func newScopeMetrics(orig *otlpmetrics.ScopeMetrics, state *internal.State) ScopeMetrics {
	return ScopeMetrics{orig: orig, state: state}
}

// NewScopeMetrics creates a new empty ScopeMetrics.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewScopeMetrics() ScopeMetrics {
	state := internal.StateMutable
	return newScopeMetrics(otlpmetrics.ScopeMetrics_builder{}.Build(), &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ScopeMetrics) MoveTo(dest ScopeMetrics) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	*dest.orig = *ms.orig
	*ms.orig = otlpmetrics.ScopeMetrics{}
}

// Scope returns the scope associated with this ScopeMetrics.
// accessorsMessageValueTemplate
func (ms ScopeMetrics) Scope() pcommon.InstrumentationScope {
	if !ms.orig.HasScope() {
		ms.orig.SetScope(&otlpcommon.InstrumentationScope{})
	}
	return pcommon.InstrumentationScope(internal.NewInstrumentationScope(ms.orig.GetScope(), ms.state))
}

// SchemaUrl returns the schemaurl associated with this ScopeMetrics.
// accessorsPrimitiveTemplate
func (ms ScopeMetrics) SchemaUrl() string {
	return ms.orig.GetSchemaUrl()
}

// SetSchemaUrl replaces the schemaurl associated with this ScopeMetrics.
func (ms ScopeMetrics) SetSchemaUrl(v string) {
	ms.state.AssertMutable()
	ms.orig.SetSchemaUrl(v)
}

// Metrics returns the Metrics associated with this ScopeMetrics.
// accessorSliceTemplate
func (ms ScopeMetrics) Metrics() MetricSlice {
	if ms.orig.GetMetrics() == nil {
		ms.orig.SetMetrics(utils.GetEmptyPointer(ms.orig.GetMetrics()))
	}
	sl := ms.orig.GetMetrics()
	return newMetricSlice(&sl, ms.state)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ScopeMetrics) CopyTo(dest ScopeMetrics) {
	dest.state.AssertMutable()
	ms.Scope().CopyTo(dest.Scope())
	dest.SetSchemaUrl(ms.SchemaUrl())
	ms.Metrics().CopyTo(dest.Metrics())
}
