// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pmetric

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ExponentialHistogramDataPointSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type ExponentialHistogramDataPointSliceAccessor interface {
	SetExponentialHistogramDataPoints([]*otlpmetrics.ExponentialHistogramDataPoint)
	GetExponentialHistogramDataPoints() []*otlpmetrics.ExponentialHistogramDataPoint
}

// ExponentialHistogramDataPointSlice logically represents a slice of ExponentialHistogramDataPoint.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewExponentialHistogramDataPointSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ExponentialHistogramDataPointSlice struct {
	orig  ExponentialHistogramDataPointSliceAccessor
	state *internal.State
}

func newExponentialHistogramDataPointSlice(orig ExponentialHistogramDataPointSliceAccessor, state *internal.State) ExponentialHistogramDataPointSlice {
	return ExponentialHistogramDataPointSlice{orig: orig, state: state}
}

// NewExponentialHistogramDataPointSlice creates a ExponentialHistogramDataPointSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewExponentialHistogramDataPointSlice() ExponentialHistogramDataPointSlice {
	state := internal.StateMutable
	return newExponentialHistogramDataPointSlice(&otlpmetric.ExponentialHistogram{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewExponentialHistogramDataPointSlice()".
func (es ExponentialHistogramDataPointSlice) Len() int {
	return len(es.orig.GetExponentialHistogramDataPoints())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ExponentialHistogramDataPointSlice) At(i int) ExponentialHistogramDataPoint {
	return newExponentialHistogramDataPoint(es.orig.GetExponentialHistogramDataPoints()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ExponentialHistogramDataPointSlice can be initialized:
//
//	es := NewExponentialHistogramDataPointSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ExponentialHistogramDataPointSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetExponentialHistogramDataPoints())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpmetrics.ExponentialHistogramDataPoint, len(es.orig.GetExponentialHistogramDataPoints()), newCap)
	copy(newOrig, es.orig.GetExponentialHistogramDataPoints())
	es.orig.SetExponentialHistogramDataPoints(newOrig)
}

// AppendEmpty will append to the end of the slice an empty ExponentialHistogramDataPoint.
// It returns the newly added ExponentialHistogramDataPoint.
func (es ExponentialHistogramDataPointSlice) AppendEmpty() ExponentialHistogramDataPoint {
	es.state.AssertMutable()
	es.orig.SetExponentialHistogramDataPoints(append(es.orig.GetExponentialHistogramDataPoints(), &otlpmetrics.ExponentialHistogramDataPoint{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ExponentialHistogramDataPointSlice) MoveAndAppendTo(dest ExponentialHistogramDataPointSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetExponentialHistogramDataPoints() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetExponentialHistogramDataPoints(es.orig.GetExponentialHistogramDataPoints())
	} else {
		dest.orig.SetExponentialHistogramDataPoints(append(dest.orig.GetExponentialHistogramDataPoints(), es.orig.GetExponentialHistogramDataPoints()...))
	}
	es.orig.SetExponentialHistogramDataPoints(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ExponentialHistogramDataPointSlice) RemoveIf(f func(ExponentialHistogramDataPoint) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetExponentialHistogramDataPoints()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetExponentialHistogramDataPoints()[newLen] = es.orig.GetExponentialHistogramDataPoints()[i]
		newLen++
	}
	es.orig.SetExponentialHistogramDataPoints(es.orig.GetExponentialHistogramDataPoints()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ExponentialHistogramDataPointSlice) CopyTo(dest ExponentialHistogramDataPointSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetExponentialHistogramDataPoints())
	if srcLen <= destCap {
		dest.orig.SetExponentialHistogramDataPoints(dest.orig.GetExponentialHistogramDataPoints()[:srcLen:destCap])
		for i := range es.orig.GetExponentialHistogramDataPoints() {
			newExponentialHistogramDataPoint(es.orig.GetExponentialHistogramDataPoints()[i], es.state).CopyTo(newExponentialHistogramDataPoint(dest.orig.GetExponentialHistogramDataPoints()[i], dest.state))
		}
		return
	}
	origs := make([]otlpmetrics.ExponentialHistogramDataPoint, srcLen)
	wrappers := make([]*otlpmetrics.ExponentialHistogramDataPoint, srcLen)
	for i := range es.orig.GetExponentialHistogramDataPoints() {
		wrappers[i] = &origs[i]
		newExponentialHistogramDataPoint(es.orig.GetExponentialHistogramDataPoints()[i], es.state).CopyTo(newExponentialHistogramDataPoint(wrappers[i], dest.state))
	}
	dest.orig.SetExponentialHistogramDataPoints(wrappers)
}

// Sort sorts the ExponentialHistogramDataPoint elements within ExponentialHistogramDataPointSlice given the
// provided less function so that two instances of ExponentialHistogramDataPointSlice
// can be compared.
func (es ExponentialHistogramDataPointSlice) Sort(less func(a, b ExponentialHistogramDataPoint) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetExponentialHistogramDataPoints(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
