// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message.go.tmpl

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	"go.opentelemetry.io/collector/pdata/pcommon/utils"
)

// Sum represents the type of a numeric metric that is calculated as a sum of all reported measurements over a time interval.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewSum function to create new instances.
// Important: zero-initialized instance is not valid for use.
type Sum struct {
	orig  *otlpmetrics.Sum
	state *internal.State
}

func newSum(orig *otlpmetrics.Sum, state *internal.State) Sum {
	return Sum{orig: orig, state: state}
}

// NewSum creates a new empty Sum.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewSum() Sum {
	state := internal.StateMutable
	return newSum(otlpmetrics.Sum_builder{}.Build(), &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms Sum) MoveTo(dest Sum) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	*dest.orig = *ms.orig
	*ms.orig = otlpmetrics.Sum{}
}

// AggregationTemporality returns the aggregationtemporality associated with this Sum.
func (ms Sum) AggregationTemporality() AggregationTemporality {
	return AggregationTemporality(ms.orig.GetAggregationTemporality())
}

// SetAggregationTemporality replaces the aggregationtemporality associated with this Sum.
func (ms Sum) SetAggregationTemporality(v AggregationTemporality) {
	ms.state.AssertMutable()
	ms.orig.SetAggregationTemporality(otlpmetrics.AggregationTemporality(v))
}

// IsMonotonic returns the ismonotonic associated with this Sum.
// accessorsPrimitiveTemplate
func (ms Sum) IsMonotonic() bool {
	return ms.orig.GetIsMonotonic()
}

// SetIsMonotonic replaces the ismonotonic associated with this Sum.
func (ms Sum) SetIsMonotonic(v bool) {
	ms.state.AssertMutable()
	ms.orig.SetIsMonotonic(v)
}

// DataPoints returns the DataPoints associated with this Sum.
// accessorSliceTemplate
func (ms Sum) DataPoints() NumberDataPointSlice {
	if ms.orig.GetDataPoints() == nil {
		ms.orig.SetDataPoints(utils.GetEmptyPointer(ms.orig.GetDataPoints()))
	}
	sl := ms.orig.GetDataPoints()
	return newNumberDataPointSlice(&sl, ms.state)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms Sum) CopyTo(dest Sum) {
	dest.state.AssertMutable()
	dest.SetAggregationTemporality(ms.AggregationTemporality())
	dest.SetIsMonotonic(ms.IsMonotonic())
	ms.DataPoints().CopyTo(dest.DataPoints())
}
