// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pmetric

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ScopeMetricsSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type ScopeMetricsSliceAccessor interface {
	SetScopeMetrics([]*otlpmetrics.ScopeMetrics)
	GetScopeMetrics() []*otlpmetrics.ScopeMetrics
}

// ScopeMetricsSlice logically represents a slice of ScopeMetrics.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewScopeMetricsSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ScopeMetricsSlice struct {
	orig  ScopeMetricsSliceAccessor
	state *internal.State
}

func newScopeMetricsSlice(orig ScopeMetricsSliceAccessor, state *internal.State) ScopeMetricsSlice {
	return ScopeMetricsSlice{orig: orig, state: state}
}

// NewScopeMetricsSlice creates a ScopeMetricsSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewScopeMetricsSlice() ScopeMetricsSlice {
	state := internal.StateMutable
	return newScopeMetricsSlice(&otlpmetrics.ResourceMetrics{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewScopeMetricsSlice()".
func (es ScopeMetricsSlice) Len() int {
	return len(es.orig.GetScopeMetrics())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ScopeMetricsSlice) At(i int) ScopeMetrics {
	return newScopeMetrics(es.orig.GetScopeMetrics()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ScopeMetricsSlice can be initialized:
//
//	es := NewScopeMetricsSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ScopeMetricsSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetScopeMetrics())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpmetrics.ScopeMetrics, len(es.orig.GetScopeMetrics()), newCap)
	copy(newOrig, es.orig.GetScopeMetrics())
	es.orig.SetScopeMetrics(newOrig)
}

// AppendEmpty will append to the end of the slice an empty ScopeMetrics.
// It returns the newly added ScopeMetrics.
func (es ScopeMetricsSlice) AppendEmpty() ScopeMetrics {
	es.state.AssertMutable()
	es.orig.SetScopeMetrics(append(es.orig.GetScopeMetrics(), &otlpmetrics.ScopeMetrics{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ScopeMetricsSlice) MoveAndAppendTo(dest ScopeMetricsSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetScopeMetrics() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetScopeMetrics(es.orig.GetScopeMetrics())
	} else {
		dest.orig.SetScopeMetrics(append(dest.orig.GetScopeMetrics(), es.orig.GetScopeMetrics()...))
	}
	es.orig.SetScopeMetrics(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ScopeMetricsSlice) RemoveIf(f func(ScopeMetrics) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetScopeMetrics()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetScopeMetrics()[newLen] = es.orig.GetScopeMetrics()[i]
		newLen++
	}
	es.orig.SetScopeMetrics(es.orig.GetScopeMetrics()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ScopeMetricsSlice) CopyTo(dest ScopeMetricsSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetScopeMetrics())
	if srcLen <= destCap {
		dest.orig.SetScopeMetrics(dest.orig.GetScopeMetrics()[:srcLen:destCap])
		for i := range es.orig.GetScopeMetrics() {
			newScopeMetrics(es.orig.GetScopeMetrics()[i], es.state).CopyTo(newScopeMetrics(dest.orig.GetScopeMetrics()[i], dest.state))
		}
		return
	}
	origs := make([]otlpmetrics.ScopeMetrics, srcLen)
	wrappers := make([]*otlpmetrics.ScopeMetrics, srcLen)
	for i := range es.orig.GetScopeMetrics() {
		wrappers[i] = &origs[i]
		newScopeMetrics(es.orig.GetScopeMetrics()[i], es.state).CopyTo(newScopeMetrics(wrappers[i], dest.state))
	}
	dest.orig.SetScopeMetrics(wrappers)
}

// Sort sorts the ScopeMetrics elements within ScopeMetricsSlice given the
// provided less function so that two instances of ScopeMetricsSlice
// can be compared.
func (es ScopeMetricsSlice) Sort(less func(a, b ScopeMetrics) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetScopeMetrics(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
