// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pmetric

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
)

// SummaryDataPointValueAtQuantileSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type SummaryDataPointValueAtQuantileSliceAccessor interface {
	SetQuantileValues([]*otlpmetrics.SummaryDataPoint_ValueAtQuantile)
	GetQuantileValues() []*otlpmetrics.SummaryDataPoint_ValueAtQuantile
}

// SummaryDataPointValueAtQuantileSlice logically represents a slice of SummaryDataPointValueAtQuantile.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewSummaryDataPointValueAtQuantileSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type SummaryDataPointValueAtQuantileSlice struct {
	orig  SummaryDataPointValueAtQuantileSliceAccessor
	state *internal.State
}

func newSummaryDataPointValueAtQuantileSlice(orig SummaryDataPointValueAtQuantileSliceAccessor, state *internal.State) SummaryDataPointValueAtQuantileSlice {
	return SummaryDataPointValueAtQuantileSlice{orig: orig, state: state}
}

// NewSummaryDataPointValueAtQuantileSlice creates a SummaryDataPointValueAtQuantileSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewSummaryDataPointValueAtQuantileSlice() SummaryDataPointValueAtQuantileSlice {
	state := internal.StateMutable
	return newSummaryDataPointValueAtQuantileSlice(&otlpmetrics.SummaryDataPoint{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewSummaryDataPointValueAtQuantileSlice()".
func (es SummaryDataPointValueAtQuantileSlice) Len() int {
	return len(es.orig.GetQuantileValues())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es SummaryDataPointValueAtQuantileSlice) At(i int) SummaryDataPointValueAtQuantile {
	return newSummaryDataPointValueAtQuantile(es.orig.GetQuantileValues()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new SummaryDataPointValueAtQuantileSlice can be initialized:
//
//	es := NewSummaryDataPointValueAtQuantileSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es SummaryDataPointValueAtQuantileSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetQuantileValues())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpmetrics.SummaryDataPoint_ValueAtQuantile, len(es.orig.GetQuantileValues()), newCap)
	copy(newOrig, es.orig.GetQuantileValues())
	es.orig.SetQuantileValues(newOrig)
}

// AppendEmpty will append to the end of the slice an empty SummaryDataPointValueAtQuantile.
// It returns the newly added SummaryDataPointValueAtQuantile.
func (es SummaryDataPointValueAtQuantileSlice) AppendEmpty() SummaryDataPointValueAtQuantile {
	es.state.AssertMutable()
	es.orig.SetQuantileValues(append(es.orig.GetQuantileValues(), &otlpmetrics.SummaryDataPoint_ValueAtQuantile{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es SummaryDataPointValueAtQuantileSlice) MoveAndAppendTo(dest SummaryDataPointValueAtQuantileSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetQuantileValues() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetQuantileValues(es.orig.GetQuantileValues())
	} else {
		dest.orig.SetQuantileValues(append(dest.orig.GetQuantileValues(), es.orig.GetQuantileValues()...))
	}
	es.orig.SetQuantileValues(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es SummaryDataPointValueAtQuantileSlice) RemoveIf(f func(SummaryDataPointValueAtQuantile) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetQuantileValues()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetQuantileValues()[newLen] = es.orig.GetQuantileValues()[i]
		newLen++
	}
	es.orig.SetQuantileValues(es.orig.GetQuantileValues()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es SummaryDataPointValueAtQuantileSlice) CopyTo(dest SummaryDataPointValueAtQuantileSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetQuantileValues())
	if srcLen <= destCap {
		dest.orig.SetQuantileValues(dest.orig.GetQuantileValues()[:srcLen:destCap])
		for i := range es.orig.GetQuantileValues() {
			newSummaryDataPointValueAtQuantile(es.orig.GetQuantileValues()[i], es.state).CopyTo(newSummaryDataPointValueAtQuantile(dest.orig.GetQuantileValues()[i], dest.state))
		}
		return
	}
	origs := make([]otlpmetrics.SummaryDataPoint_ValueAtQuantile, srcLen)
	wrappers := make([]*otlpmetrics.SummaryDataPoint_ValueAtQuantile, srcLen)
	for i := range es.orig.GetQuantileValues() {
		wrappers[i] = &origs[i]
		newSummaryDataPointValueAtQuantile(es.orig.GetQuantileValues()[i], es.state).CopyTo(newSummaryDataPointValueAtQuantile(wrappers[i], dest.state))
	}
	dest.orig.SetQuantileValues(wrappers)
}

// Sort sorts the SummaryDataPointValueAtQuantile elements within SummaryDataPointValueAtQuantileSlice given the
// provided less function so that two instances of SummaryDataPointValueAtQuantileSlice
// can be compared.
func (es SummaryDataPointValueAtQuantileSlice) Sort(less func(a, b SummaryDataPointValueAtQuantile) bool) {
	es.state.AssertMutable()
	sort.SliceStable(es.orig.GetQuantileValues(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
