// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// slice.go.tmpl

package pmetric

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ExemplarSliceAccessor is a slice accessor that is used to solve the problem
// of accessing the slice using the Protobuf Opaque API
type ExemplarSliceAccessor interface {
	SetExemplars([]*otlpmetrics.Exemplar)
	GetExemplars() []*otlpmetrics.Exemplar
}

// ExemplarSlice logically represents a slice of Exemplar.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewExemplarSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ExemplarSlice struct {
	orig  ExemplarSliceAccessor
	state *internal.State
}

func newExemplarSlice(orig ExemplarSliceAccessor, state *internal.State) ExemplarSlice {
	return ExemplarSlice{orig: orig, state: state}
}

// NewExemplarSlice creates a ExemplarSlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewExemplarSlice() ExemplarSlice {
	state := internal.StateMutable
	return newExemplarSlice(&otlpmetrics.HistogramDataPoint{}, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewExemplarSlice()".
func (es ExemplarSlice) Len() int {
	return len(es.orig.GetExemplars())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ExemplarSlice) At(i int) Exemplar {
	return newExemplar(es.orig.GetExemplars()[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ExemplarSlice can be initialized:
//
//	es := NewExemplarSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ExemplarSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(es.orig.GetExemplars())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpmetrics.Exemplar, len(es.orig.GetExemplars()), newCap)
	copy(newOrig, es.orig.GetExemplars())
	es.orig.SetExemplars(newOrig)
}

// AppendEmpty will append to the end of the slice an empty Exemplar.
// It returns the newly added Exemplar.
func (es ExemplarSlice) AppendEmpty() Exemplar {
	es.state.AssertMutable()
	es.orig.SetExemplars(append(es.orig.GetExemplars(), &otlpmetrics.Exemplar{}))
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ExemplarSlice) MoveAndAppendTo(dest ExemplarSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if dest.orig.GetExemplars() == nil {
		// We can simply move the entire vector and avoid any allocations.
		dest.orig.SetExemplars(es.orig.GetExemplars())
	} else {
		dest.orig.SetExemplars(append(dest.orig.GetExemplars(), es.orig.GetExemplars()...))
	}
	es.orig.SetExemplars(nil)
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ExemplarSlice) RemoveIf(f func(Exemplar) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(es.orig.GetExemplars()); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		es.orig.GetExemplars()[newLen] = es.orig.GetExemplars()[i]
		newLen++
	}
	es.orig.SetExemplars(es.orig.GetExemplars()[:newLen])
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ExemplarSlice) CopyTo(dest ExemplarSlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(dest.orig.GetExemplars())
	if srcLen <= destCap {
		dest.orig.SetExemplars(dest.orig.GetExemplars()[:srcLen:destCap])
	} else {
		(dest.orig).SetExemplars(make([]*otlpmetrics.Exemplar, srcLen))
	}
	for i := range es.orig.GetExemplars() {
		newExemplar(es.orig.GetExemplars()[i], es.state).CopyTo(newExemplar(dest.orig.GetExemplars()[i], dest.state))
	}
}
