// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message.go.tmpl

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pcommon/utils"
)

// ExponentialHistogramDataPoint is a single data point in a timeseries that describes the
// time-varying values of a ExponentialHistogram of double values. A ExponentialHistogram contains
// summary statistics for a population of values, it may optionally contain the
// distribution of those values across a set of buckets.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewExponentialHistogramDataPoint function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ExponentialHistogramDataPoint struct {
	orig  *otlpmetrics.ExponentialHistogramDataPoint
	state *internal.State
}

func newExponentialHistogramDataPoint(orig *otlpmetrics.ExponentialHistogramDataPoint, state *internal.State) ExponentialHistogramDataPoint {
	return ExponentialHistogramDataPoint{orig: orig, state: state}
}

// NewExponentialHistogramDataPoint creates a new empty ExponentialHistogramDataPoint.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewExponentialHistogramDataPoint() ExponentialHistogramDataPoint {
	state := internal.StateMutable
	return newExponentialHistogramDataPoint(otlpmetrics.ExponentialHistogramDataPoint_builder{}.Build(), &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ExponentialHistogramDataPoint) MoveTo(dest ExponentialHistogramDataPoint) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	*dest.orig = *ms.orig
	*ms.orig = otlpmetrics.ExponentialHistogramDataPoint{}
}

// Attributes returns the Attributes associated with this ExponentialHistogramDataPoint.
// accessorSliceTemplate
func (ms ExponentialHistogramDataPoint) Attributes() pcommon.Map {
	if ms.orig.GetAttributes() == nil {
		ms.orig.SetAttributes(utils.GetEmptyPointer(ms.orig.GetAttributes()))
	}
	return pcommon.Map(internal.NewMap(utils.Ref(ms.orig.GetAttributes()), ms.state))
}

// StartTimestamp returns the starttimestamp associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) StartTimestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.GetStartTimeUnixNano())
}

// SetStartTimestamp replaces the starttimestamp associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetStartTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.SetStartTimeUnixNano(uint64(v))
}

// Timestamp returns the timestamp associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) Timestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.GetTimeUnixNano())
}

// SetTimestamp replaces the timestamp associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.SetTimeUnixNano(uint64(v))
}

// Count returns the count associated with this ExponentialHistogramDataPoint.
// accessorsPrimitiveTemplate
func (ms ExponentialHistogramDataPoint) Count() uint64 {
	return ms.orig.GetCount()
}

// SetCount replaces the count associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetCount(v uint64) {
	ms.state.AssertMutable()
	ms.orig.SetCount(v)
}

// Scale returns the scale associated with this ExponentialHistogramDataPoint.
// accessorsPrimitiveTemplate
func (ms ExponentialHistogramDataPoint) Scale() int32 {
	return ms.orig.GetScale()
}

// SetScale replaces the scale associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetScale(v int32) {
	ms.state.AssertMutable()
	ms.orig.SetScale(v)
}

// ZeroCount returns the zerocount associated with this ExponentialHistogramDataPoint.
// accessorsPrimitiveTemplate
func (ms ExponentialHistogramDataPoint) ZeroCount() uint64 {
	return ms.orig.GetZeroCount()
}

// SetZeroCount replaces the zerocount associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetZeroCount(v uint64) {
	ms.state.AssertMutable()
	ms.orig.SetZeroCount(v)
}

// Positive returns the positive associated with this ExponentialHistogramDataPoint.
// accessorsMessageValueTemplate
func (ms ExponentialHistogramDataPoint) Positive() ExponentialHistogramDataPointBuckets {
	if !ms.orig.HasPositive() {
		ms.orig.SetPositive(&otlpmetrics.ExponentialHistogramDataPoint_Buckets{})
	}
	return newExponentialHistogramDataPointBuckets(ms.orig.GetPositive(), ms.state)
}

// Negative returns the negative associated with this ExponentialHistogramDataPoint.
// accessorsMessageValueTemplate
func (ms ExponentialHistogramDataPoint) Negative() ExponentialHistogramDataPointBuckets {
	if !ms.orig.HasNegative() {
		ms.orig.SetNegative(&otlpmetrics.ExponentialHistogramDataPoint_Buckets{})
	}
	return newExponentialHistogramDataPointBuckets(ms.orig.GetNegative(), ms.state)
}

// Exemplars returns the Exemplars associated with this ExponentialHistogramDataPoint.
// accessorSliceTemplate
func (ms ExponentialHistogramDataPoint) Exemplars() ExemplarSlice {
	if ms.orig.GetExemplars() == nil {
	}
	sl := ms.orig.GetExemplars()
	return newExemplarSlice(&sl, ms.state)
}

// Flags returns the flags associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) Flags() DataPointFlags {
	return DataPointFlags(ms.orig.GetFlags())
}

// SetFlags replaces the flags associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetFlags(v DataPointFlags) {
	ms.state.AssertMutable()
	ms.orig.SetFlags(uint32(v))
}

// Sum returns the sum associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) Sum() float64 {
	return ms.orig.GetSum()
}

// HasSum returns true if the ExponentialHistogramDataPoint contains a
// Sum value, false otherwise.
func (ms ExponentialHistogramDataPoint) HasSum() bool {
	return ms.orig.HasSum()
}

// SetSum replaces the sum associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetSum(v float64) {
	ms.state.AssertMutable()
	ms.orig.SetSum(v)
}

// RemoveSum removes the sum associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) RemoveSum() {
	ms.state.AssertMutable()
	ms.orig.ClearSum()
}

// Min returns the min associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) Min() float64 {
	return ms.orig.GetMin()
}

// HasMin returns true if the ExponentialHistogramDataPoint contains a
// Min value, false otherwise.
func (ms ExponentialHistogramDataPoint) HasMin() bool {
	return ms.orig.HasMin()
}

// SetMin replaces the min associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetMin(v float64) {
	ms.state.AssertMutable()
	ms.orig.SetMin(v)
}

// RemoveMin removes the min associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) RemoveMin() {
	ms.state.AssertMutable()
	ms.orig.ClearMin()
}

// Max returns the max associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) Max() float64 {
	return ms.orig.GetMax()
}

// HasMax returns true if the ExponentialHistogramDataPoint contains a
// Max value, false otherwise.
func (ms ExponentialHistogramDataPoint) HasMax() bool {
	return ms.orig.HasMax()
}

// SetMax replaces the max associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetMax(v float64) {
	ms.state.AssertMutable()
	ms.orig.SetMax(v)
}

// RemoveMax removes the max associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) RemoveMax() {
	ms.state.AssertMutable()
	ms.orig.ClearMax()
}

// ZeroThreshold returns the zerothreshold associated with this ExponentialHistogramDataPoint.
// accessorsPrimitiveTemplate
func (ms ExponentialHistogramDataPoint) ZeroThreshold() float64 {
	return ms.orig.GetZeroThreshold()
}

// SetZeroThreshold replaces the zerothreshold associated with this ExponentialHistogramDataPoint.
func (ms ExponentialHistogramDataPoint) SetZeroThreshold(v float64) {
	ms.state.AssertMutable()
	ms.orig.SetZeroThreshold(v)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ExponentialHistogramDataPoint) CopyTo(dest ExponentialHistogramDataPoint) {
	dest.state.AssertMutable()
	ms.Attributes().CopyTo(dest.Attributes())
	dest.SetStartTimestamp(ms.StartTimestamp())
	dest.SetTimestamp(ms.Timestamp())
	dest.SetCount(ms.Count())
	dest.SetScale(ms.Scale())
	dest.SetZeroCount(ms.ZeroCount())
	ms.Positive().CopyTo(dest.Positive())
	ms.Negative().CopyTo(dest.Negative())
	ms.Exemplars().CopyTo(dest.Exemplars())
	dest.SetFlags(ms.Flags())
	if ms.HasSum() {
		dest.SetSum(ms.Sum())
	}

	if ms.HasMin() {
		dest.SetMin(ms.Min())
	}

	if ms.HasMax() {
		dest.SetMax(ms.Max())
	}

	dest.SetZeroThreshold(ms.ZeroThreshold())
}
