// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

// message.go.tmpl

package pcommon

import (
	"go.opentelemetry.io/collector/pdata/internal"
	otlpresource "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/pdata/pcommon/utils"
)

// Resource is a message representing the resource information.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewResource function to create new instances.
// Important: zero-initialized instance is not valid for use.
type Resource internal.Resource

func newResource(orig *otlpresource.Resource, state *internal.State) Resource {
	return Resource(internal.NewResource(orig, state))
}

// NewResource creates a new empty Resource.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewResource() Resource {
	state := internal.StateMutable
	return newResource(otlpresource.Resource_builder{}.Build(), &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms Resource) MoveTo(dest Resource) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	*dest.getOrig() = *ms.getOrig()
	*ms.getOrig() = otlpresource.Resource{}
}

func (ms Resource) getOrig() *otlpresource.Resource {
	return internal.GetOrigResource(internal.Resource(ms))
}

func (ms Resource) getState() *internal.State {
	return internal.GetResourceState(internal.Resource(ms))
}

// Attributes returns the Attributes associated with this Resource.
// accessorSliceTemplate
func (ms Resource) Attributes() Map {
	return Map(internal.NewMap(utils.Ref(ms.getOrig().GetAttributes()), internal.GetResourceState(internal.Resource(ms))))
}

// DroppedAttributesCount returns the droppedattributescount associated with this Resource.
// accessorsPrimitiveTemplate
func (ms Resource) DroppedAttributesCount() uint32 {
	return ms.getOrig().GetDroppedAttributesCount()
}

// SetDroppedAttributesCount replaces the droppedattributescount associated with this Resource.
func (ms Resource) SetDroppedAttributesCount(v uint32) {
	ms.getState().AssertMutable()
	ms.getOrig().SetDroppedAttributesCount(v)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms Resource) CopyTo(dest Resource) {
	dest.getState().AssertMutable()
	ms.Attributes().CopyTo(dest.Attributes())
	dest.SetDroppedAttributesCount(ms.DroppedAttributesCount())
}
